version: '3.8'
services:
  front:
    build:
      context: ./front
    ports:
      - "80:80"

  back:
    build:
      context: ./back
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    depends_on:
      - db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres:12
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=2helDNX3dVoGsgMUbfXljXP8vuz_JoJTo8y4yDf4sp4hqM3u
    command: ngrok http front:80 --region=auto --log=stdout 
  
  
  
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
